[profile.default]
src = "src"
out = "out"
test = "foundry-test"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
solc_version = "0.8.24"
evm_version = "cancun"
